export { default as ImgCourse } from './homework.png'
export { default as ImgCourse2 } from './online-learning.png'
export { default as ImgService } from './website.png'
export { default as ImgCourseColor } from './webinar.png'
export { default as ImgServiceColor } from './application.png'
export { default as ImgCourse3 } from './course-logo.png'
export { default as ImgCourse4 } from './course-logo-black.png'
export { default as ImgArrow } from './right-arrow.png'
export { default as ImgNeural } from './neural.png'
export { default as ImgRound } from './global-network-blue.png'
export { default as ImgCheck } from './check.png'

export { default as ImgAws } from './aws-png.png'
export { default as ImgDocker } from './docker-png.png'
export { default as ImgMongo } from './mongo-png.png'
export { default as ImgTs } from './ts-png.png'
export { default as ImgVanilla } from './vanilla-png.png'
export { default as ImgGit } from './git-png.png'
export { default as ImgReact } from './react-png.png'
export { default as ImgNode } from './nodejs-png.png'
export { default as ImgJs } from './js-png.png'

export { default as ImgFlyer1 } from './lsc_feb_1.png'
export { default as ImgFlyer2 } from './lsc_mar_1.png'
export { default as ImgFlyer3 } from './se-1-jan.png'
export { default as ImgFlyer4 } from './se-2-jan.png'
