export { default as ImgCourse } from './homework.png'
export { default as ImgCourse2 } from './online-learning.png'
export { default as ImgService } from './website.png'
export { default as ImgCourseColor } from './webinar.png'
export { default as ImgServiceColor } from './application.png'
export { default as ImgCourse3 } from './course-logo.png'
export { default as ImgCourse4 } from './course-logo-black.png'
export { default as ImgArrow } from './right-arrow.png'
export { default as ImgNeural } from './neural.png'
export { default as ImgRound } from './global-network-blue.png'
export { default as ImgCheck } from './check.png'

export { default as ImgAws } from './aws-png.png'
export { default as ImgDocker } from './docker-png.png'
export { default as ImgMongo } from './mongo-png.png'
export { default as ImgTs } from './ts-png.png'
export { default as ImgVanilla } from './vanilla-png.png'
export { default as ImgGit } from './git-png.png'
export { default as ImgReact } from './react-png.png'
export { default as ImgNode } from './nodejs-png.png'
export { default as ImgJs } from './js-png.png'

export { default as ImgFlyer1 } from './lsc_feb_1.png'
export { default as ImgFlyer2 } from './lsc_mar_1.png'
export { default as ImgFlyer3 } from './se-1-jan.png'
export { default as ImgFlyer4 } from './se-2-jan.png'

export { default as BannerEnrichment } from './coding-enrichment.png'
export { default as BannerSkillset } from './skill-set.png'

export { default as RegistrationSteps } from './reg-steps.png'
export { default as Preview1 } from './preview-1.png'
export { default as Preview2 } from './preview-2.png'
export { default as Preview3 } from './preview-3.png'
export { default as Preview4 } from './preview-4.png'
export { default as Preview5 } from './preview-5.png'
export { default as Preview6 } from './preview-6.png'
export { default as Preview7 } from './preview-7.png'
export { default as Preview8 } from './preview-8.png'
export { default as Preview9 } from './preview-9.png'
export { default as Preview10 } from './preview-10.png'
export { default as Preview11 } from './preview-11.png'
export { default as Preview12 } from './preview-12.png'

export { default as ImgWebDesign } from './web-design.png'
export { default as ImgModalClose} from './modal-close.png'

export { default as ImgDemo1a } from './demo1-a.png'
export { default as ImgDemo1b } from './demo1-b.png'
export { default as PreviewDemo1 } from './preview-demo1.png'
